kind: Pod
apiVersion: v1
metadata:
  name: nginx-1
spec:
  volumes:
    - name: nginx-1
      persistentVolumeClaim:
        claimName: nginx-fss-volume
  containers:
    - name: nginx-1
      image: nginx
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nginx-1
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-2
spec:
  volumes:
    - name: nginx-2
      persistentVolumeClaim:
        claimName: nginx-fss-volume
  containers:
    - name: nginx-2
      image: nginx
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nginx-2
